apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resources.duck.knative.dev
spec:
  group: duck.knative.dev
  names:
    kind: Resource
    listKind: ResourceList
    plural: resources
    singular: resource
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Resource is a skeleton type wrapping all Kubernetes resources.
        It is typically used to watch arbitrary other resources (such as any Source
        or Addressable). This is not a real resource.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
