apiVersion: v1
kind: Namespace
metadata:
  name: discovery-demo
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: discovery-broker
  namespace: discovery-demo
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: discovery-broker-2
  namespace: discovery-demo
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: discovery-broker-3
  namespace: discovery-demo
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source-hello-world
  namespace: discovery-demo
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: discovery-broker
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source-hello-discovery
  namespace: discovery-demo
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello Discovery!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: discovery-broker-2
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source-hello-brno
  namespace: discovery-demo
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello Brno!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: discovery-broker-3
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
  namespace: discovery-demo
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  namespace: discovery-demo
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      ports:
        - containerPort: 8080
