apiVersion: v1
kind: Namespace
metadata:
  name: discovery-demo
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: discovery-broker
  namespace: discovery-demo
---


apiVersion: v1
kind: Service
metadata:
  name: event-display
  namespace: discovery-demo
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  namespace: discovery-demo
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      ports:
        - containerPort: 8080
