/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "knative.dev/eventing/pkg/apis/eventing/v1beta1"
)

// FakeEventTypeQueries implements EventTypeQueryInterface
type FakeEventTypeQueries struct {
	Fake *FakeEventingV1beta1
	ns   string
}

var eventtypequeriesResource = schema.GroupVersionResource{Group: "eventing.knative.dev", Version: "v1beta1", Resource: "eventtypequeries"}

var eventtypequeriesKind = schema.GroupVersionKind{Group: "eventing.knative.dev", Version: "v1beta1", Kind: "EventTypeQuery"}

// Get takes name of the eventTypeQuery, and returns the corresponding eventTypeQuery object, and an error if there is any.
func (c *FakeEventTypeQueries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EventTypeQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(eventtypequeriesResource, c.ns, name), &v1beta1.EventTypeQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EventTypeQuery), err
}

// List takes label and field selectors, and returns the list of EventTypeQueries that match those selectors.
func (c *FakeEventTypeQueries) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.EventTypeQueryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(eventtypequeriesResource, eventtypequeriesKind, c.ns, opts), &v1beta1.EventTypeQueryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.EventTypeQueryList{ListMeta: obj.(*v1beta1.EventTypeQueryList).ListMeta}
	for _, item := range obj.(*v1beta1.EventTypeQueryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eventTypeQueries.
func (c *FakeEventTypeQueries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(eventtypequeriesResource, c.ns, opts))

}

// Create takes the representation of a eventTypeQuery and creates it.  Returns the server's representation of the eventTypeQuery, and an error, if there is any.
func (c *FakeEventTypeQueries) Create(ctx context.Context, eventTypeQuery *v1beta1.EventTypeQuery, opts v1.CreateOptions) (result *v1beta1.EventTypeQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(eventtypequeriesResource, c.ns, eventTypeQuery), &v1beta1.EventTypeQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EventTypeQuery), err
}

// Update takes the representation of a eventTypeQuery and updates it. Returns the server's representation of the eventTypeQuery, and an error, if there is any.
func (c *FakeEventTypeQueries) Update(ctx context.Context, eventTypeQuery *v1beta1.EventTypeQuery, opts v1.UpdateOptions) (result *v1beta1.EventTypeQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(eventtypequeriesResource, c.ns, eventTypeQuery), &v1beta1.EventTypeQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EventTypeQuery), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEventTypeQueries) UpdateStatus(ctx context.Context, eventTypeQuery *v1beta1.EventTypeQuery, opts v1.UpdateOptions) (*v1beta1.EventTypeQuery, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(eventtypequeriesResource, "status", c.ns, eventTypeQuery), &v1beta1.EventTypeQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EventTypeQuery), err
}

// Delete takes name of the eventTypeQuery and deletes it. Returns an error if one occurs.
func (c *FakeEventTypeQueries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(eventtypequeriesResource, c.ns, name, opts), &v1beta1.EventTypeQuery{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEventTypeQueries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(eventtypequeriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.EventTypeQueryList{})
	return err
}

// Patch applies the patch and returns the patched eventTypeQuery.
func (c *FakeEventTypeQueries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.EventTypeQuery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(eventtypequeriesResource, c.ns, name, pt, data, subresources...), &v1beta1.EventTypeQuery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EventTypeQuery), err
}
